name: Release Helm Chart
on:
  push:
    branches:
      'master'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Do stuff
        run: |
          echo "This workflow will trigger a different workflow"
