name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: false

jobs:
  job1:
    name: Mesheryctl Pattern Action 
    if: github.repository == 'sayantan1413/ci-tests'
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl pattern
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
      - name: Do stuffs
        # any command that mesheryctl is capable of handling
        run: |
          mesheryctl pattern apply pat.yml