name: Random run
on:
  workflow_dispatch:
    inputs:
      service_mesh:
        description: "none"
        required: true

jobs:
  job1:
    name: blah
    runs-on: ubuntu-latest
    env:
      service_mesh: ${{ github.event.inputs.service_mesh }}
    steps:
      - name: Get mesheryctl
        run:
          service_mesh_adapter=meshery-$service_mesh
          curl -L https://git.io/meshery | DEPLOY_MESHERY=false bash -

          mesheryctl system context create new-context1 --adapters={$service_mesh_adapter} --platform docker --url http://localhost:9081 --set --yes;
          sleep 2;
          mesheryctl system context create new-context2 --adapters '$service_mesh_adapter' --platform docker --url http://localhost:9081 --set;
          sleep 2;
          mesheryctl system context create new-context3 --adapters "$service_mesh_adapter" --platform docker --url http://localhost:9081 --set;
          sleep 2;
          mesheryctl system context create new-context4 --adapters "'$service_mesh_adapter'" --platform docker --url http://localhost:9081 --set;
          sleep 2;
          mesheryctl system context create new-context5 --adapters '$service_mesh_adapter' --platform docker --url http://localhost:9081 --set;
          sleep 2

          cat ~/.meshery/config.yaml
