name: Meshery
on:
  workflow_dispatch:
    inputs:
      provider_token:
        description: "Meshery auth token"
        required: true

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: mesheryctl action
        uses: DelusionalOptimist/mesheryctl-smi-conformance-action@mesh-deploy
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          service_mesh: open_service_mesh
