name: Meshery
on:
  push:
    branches:
      - 'master'

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: Fetch Linkerd Binary
        run: |
          curl -sL https://run.linkerd.io/install | sh

      - name: mesheryctl action
        uses: DelusionalOptimist/mesheryctl-smi-conformance-action@mesh-deploy
        with:
          provider_token: ${{ secrets.PROVIDER_TOKEN }}
          platform: docker
          spec: smi
          service_mesh: linkerd
          path_to_binary: "~/.linkerd2/bin/linkerd"
