name: SMP cron job
on:
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: "false"
        default: ${{ secrets.PROVIDER_TOKEN }}
      profile_name:
        description: "name of the performance profile to use"
        required: "false"
        default: SMP_CRON_ISTIO
    #  schedule:
    #    - cron: '*/30 * * * *'

jobs:
  job1:
    name: Run Performance Test
    runs-on: ubuntu-latest
    steps:
      #- name: checkout
      #  uses: actions/checkout@v2
      #  with:
      #   ref: 'perf'

      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: Performance test
        #uses: layer5io/meshery-smp-action@master
        uses: DelusionalOptimist/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: kubernetes
          profile_name: ${{ github.event.inputs.profile_name }}
