name: Meshery
on:
  workflow_dispatch:
    inputs:
      provider_token:
        description: "Meshery auth token"
        required: true

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: Fetch OSM Binary
        run: |
          curl -LO https://github.com/openservicemesh/osm/releases/download/v0.6.0/osm-v0.6.0-linux-amd64.tar.gz
          tar -xzf ./osm-v0.6.0-linux-amd64.tar.gz
          export PATH="$PWD:~/linux-amd64/"

      - name: mesheryctl action
        uses: DelusionalOptimist/mesheryctl-smi-conformance-action@mesh-deploy
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: docker
          spec: smi
          service_mesh: open_service_mesh
          binary_name: "osm"
