name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "Meshery auth token"
        required: true

jobs:
  job1:
    name: Mesheryctl Pattern Actions 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub CLI example
        run: gh issue list
      - name: mesheryctl pattern action
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
      