name: SMP cron job
on:
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: false
      profile_name:
        description: "name of the performance profile to use"
        required: false
        default: SMP_CRON_ISTIO
    #  schedule:
    #    - cron: '*/30 * * * *'

# these jobs deploy a minikube cluster with k8s versions 1.20, 1.21, 1.22
# uses meshery, meshery-adapters edge-latest and mesheryctl stable-latest

# manual-job is triggered manually in case of problems with provider tokens
jobs:
  manual-job:
    name: Run Performance Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: Performance test
        #uses: layer5io/meshery-smp-action@master
        uses: DelusionalOptimist/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ github.event.inputs.provider_token }}
          platform: kubernetes
          profile_name: ${{ github.event.inputs.profile_name }}

# auto-job is triggered with a cron scehdule
  auto-job:
    name: Run Performance Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Deploy k8s
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker

      - name: Performance test
        #uses: layer5io/meshery-smp-action@master
        uses: DelusionalOptimist/meshery-smp-action@meshery-ci
        with:
          provider_token: ${{ secrets.provider_token }}
          platform: kubernetes
          profile_name: SMP_CRON_ISTIO
