name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: false

jobs:
  job1:
    name: Mesheryctl Pattern Actions 
    runs-on: ubuntu-latest
    steps:
      # deploy k8s
      - name: Deploy k8s
        if: github.repository == 'sayantan1413/ci-tests'
        uses: manusa/actions-setup-minikube@v2.4.1
        with:
          minikube version: 'v1.21.0'
          kubernetes version: 'v1.20.7'
          driver: docker
      - name: mesheryctl pattern action
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
      - name: Do stuffs
        # any command that mesheryctl is capable of handling
        run: |
          mesheryctl pattern apply pat.yml