name: Mesheryctl Pattern Action
on:
  push:
    branches:
      - 'master'
  # if manually triggering, provide a provider token yourself
  workflow_dispatch:
    inputs:
      provider_token:
        description: "token for remote provider"
        required: true

jobs:
  job1:
    name: Mesheryctl Pattern Actions 
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl pattern action
        uses: sayantan1413/mesheryctl-service-mesh-patterns-action@master
      