name: SMP-ACTION-NEW
on:
  push:
    branches:
      - 'master'

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: mesheryctl action
        uses: DelusionalOptimist/mesheryctl-actions@main
