name: Meshery
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  job1:
    name: everything
    runs-on: ubuntu-latest
    steps:
      - name: is PAT accessible?
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          echo $GITHUB_TOKEN

      - name: is GITHUB_TOKEN accessible?
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN
